services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file-transfer-server
    ports:
      - "8069:8069"
    environment:
      FLASK_SECRET_KEY: "change-this-secret"
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped
