[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "inert-transfer"
version = "0.2.8"
description = "File transfer server with PIN and encryption"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name = "Inert Tila" }
]
license = { text = "MIT" } 
keywords = ["file-transfer", "flask", "encryption", "pin"]
dependencies = [
  "Flask",
  "flask-sock",
  "cryptography",
  "itsdangerous",
  "Werkzeug",
  "waitress",
  "packaging"
]

[project.urls]
Homepage = "https://inert.netlify.app"
Repository = "https://github.com/inerttila/File-Transfer-Server"

[project.scripts]
fts = "inert_transfer.cli:main"
inert = "inert_transfer.cli:main"

[tool.setuptools]
include-package-data = true
py-modules = ["server"]
packages = ["inert_transfer"]

[tool.setuptools.data-files]
"templates" = ["templates/*.html"]
"static/css" = ["static/css/*.css"]
"static/js" = ["static/js/*.js"]
